spring.application.name=quoteapp
spring.datasource.url=jdbc:postgresql://localhost:5432/quoteapp
spring.datasource.username=quoteuser
spring.datasource.password=quotepass

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
